[build]
  functions = "functions"
  publish = "/opt/build/repo"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/"
  status = 200
  to = "/.netlify/functions/api/:splat"
